name: 
title: Subhendu Khatuya
url: 
baseurl: ""
twitter_username:
github_username:  
linkedin_username: 
description: 
permalink: /blog/:year/:month/:day/:title
theme: minima

# Conversion
markdown: kramdown

plugins:
  - "disqus-for-jekyll"
  - jekyll-feed
  - jemoji

header_pages:
  #- resume.md
  - publications.md
  - blog/index.html
  - index.md
  - projects.md
